name: CI

on:
  push:
    branches:
      - '*'

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      - run: npm ci
      - name: Set up JDK 11 for running Gradle
        uses: actions/setup-java@v3.11.0
        with:
          distribution: adopt
          java-version: 11
      - name: Prepare Android environment
        run: |
          export ANDROID_COMPILE_SDK=33
          export ANDROID_BUILD_TOOLS=33.0.1
          export ANDROID_COMMAND_LINE_TOOLS=9477386

          sudo apt-get --quiet update --yes
          sudo apt-get --quiet install --yes wget tar unzip lib32stdc++6 lib32z1
          wget --quiet --output-document=android-sdk.zip https://dl.google.com/android/repository/commandlinetools-linux-${ANDROID_COMMAND_LINE_TOOLS}_latest.zip
          unzip -d android-sdk-linux android-sdk.zip
          echo y | android-sdk-linux/cmdline-tools/bin/sdkmanager --sdk_root=. "platforms;android-${ANDROID_COMPILE_SDK}" >/dev/null
          echo y | android-sdk-linux/cmdline-tools/bin/sdkmanager --sdk_root=. "platform-tools" >/dev/null
          echo y | android-sdk-linux/cmdline-tools/bin/sdkmanager --sdk_root=. "build-tools;${ANDROID_BUILD_TOOLS}" >/dev/null
          export ANDROID_SDK_ROOT=$PWD
          export PATH=$PATH:$PWD/platform-tools/
          # temporarily disable checking for EPIPE error and use yes to accept all licenses
          set +o pipefail
          yes | android-sdk-linux/cmdline-tools/bin/sdkmanager --sdk_root=. --licenses
          set -o pipefail
      - name: Build android
        run: |
          cd example/android
          ./gradlew assembleDebug assembleAndroidTest -DtestBuildType=debug
  build-ios:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
    - name: Set up JDK 11 for running Gradle
      uses: actions/setup-java@v3.11.0
      with:
        distribution: adopt
        java-version: 11
    - run: npm ci
    - run: pod install --project-directory=example/ios
    - name: Build ios
      run: cd example/ios && xcodebuild -workspace SplunkOtelReactNativeExample.xcworkspace -scheme SplunkOtelReactNativeExample -configuration Debug CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY=""
