name: CI

on:
  pull_request:

jobs:
  version-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      - run: npm run version:check
  android-integration-tests:
    needs: version-check
    runs-on: ubuntu-latest
    permissions: read-all
    environment: integration
    env:
      SAUCE_USERNAME: ${{ secrets.SAUCE_USERNAME }}
      SAUCE_ACCESS_KEY: ${{ secrets.SAUCE_ACCESS_KEY }}
      SAUCE_TUNNEL_ID: ${{ secrets.SAUCE_TUNNEL_ID }}
    steps:
      - name: Setup sauce connect
        uses: saucelabs/sauce-connect-action@v2
        with:
          username: ${{ secrets.SAUCE_USERNAME }}
          accessKey: ${{ secrets.SAUCE_ACCESS_KEY }}
          tunnelName: ${{ secrets.SAUCE_TUNNEL_ID }}
          noSSLBumpDomains: all
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      - run: npm ci
      - run: npm run bootstrap
      - name: Set up JDK 11 for running Gradle
        uses: actions/setup-java@v3.11.0
        with:
          distribution: adopt
          java-version: 11
      - name: Prepare Android environment
        run: |
          export ANDROID_COMPILE_SDK=33
          export ANDROID_BUILD_TOOLS=33.0.1
          export ANDROID_COMMAND_LINE_TOOLS=9477386
      - name: Link react to avoid duplication
        run: cd example && npm link ../node_modules/react
      - name: Build release version
        run: |
          export ENVFILE=../.env.integration
          cd example && npm run build.release
      - name: Upload apk to saucelabs
        run: |
          curl -u "$SAUCE_USERNAME:$SAUCE_ACCESS_KEY" --location \
          --request POST 'https://api.us-west-1.saucelabs.com/v1/storage/upload' \
          --form 'payload=@"example/android/app/build/outputs/apk/release/app-release.apk"' \
          --form 'name="app-release.apk"'
      - name: Run tests
        run: cd example && npm run wdio.sauce
  build-ios:
    needs: version-check
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
    - run: npm ci
    - run: npm run bootstrap
    - name: Build ios
      run: cd example/ios && xcodebuild -workspace SplunkOtelReactNativeExample.xcworkspace -scheme SplunkOtelReactNativeExample -configuration Debug CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY=""

